version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "api-gateway/v2/modules/httpcache"

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true