on:
  schedule:
    - cron: '0 10 * * *'
name: Issue and PR hygiene
jobs:
  stale:
    uses: davron112/.github/.github/workflows/stale.yml@main
  lock-threads:
    uses: davron112/.github/.github/workflows/lock-threads.yml@main
